Enable access to isLoading `true` state
auth0/auth0-angular pull request #13
Opened 2020-07-22 17:47 UTC by stevehobbsdev

This PR changes the `isLoading$` observable emission behaviour to allow access to when the value is `true`. This is useful for the UI so that it can display some kind of loading spinner or text before the rest of the UI is available.

This PR also does some refactoring of the tests to include a couple of helpers, but also moves the setup of the service into the `it` blocks so that its creation can be controlled a bit more carefully.

2020-07-22 18:27 UTC, lbalmaceda requested changes

2020-07-22 18:27 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.service.spec.ts
> +      const service = createService();
lots and lots of `createService()`. Any reason to avoid a describe-scoped or even file-scoped `beforeEach()`?

```js
describe('when some case', () => {
    beforeEach(() => {
      createService();
    });
}
```

2020-07-22 18:27 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.service.ts
> -          this.isLoadingSubject$.complete();
I thought these 2 were needed to be called consequently. Why is it being removed now?

2020-07-22 19:58 UTC, stevehobbsdev commented on projects/auth0-angular/src/lib/auth.service.spec.ts
> +      const service = createService();
Yeah, let me revisit this. The motivation for moving it was so that the exact point of creation could be determined as a few tests need to set up something before the service is created (testing functionality that happens in the constructor), but perhaps some of that is not needed any more.

Let me clean it up a bit.

2020-07-22 20:05 UTC, stevehobbsdev commented on projects/auth0-angular/src/lib/auth.service.ts
> -          this.isLoadingSubject$.complete();
With the changes in this PR to `isLoading$`, I found that `isAuthenticated$` no longer gets notified when `isLoading$` emits a value if we manually complete it. I guess if an observable has completed, you no longer get the latest value from it.

This test never completes, for example, because the subscription happens after the `complete` call: 

```js
it('should get a value', (done) => {
    const s = new BehaviorSubject(false);
    const t = s.pipe(tap(console.log));

    s.next(true);
    s.complete();

    t.subscribe((v) => {
      console.log(v);
      done();
    });
  });
```

I'm not sure why this worked before.

2020-07-22 20:44 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.service.ts
> -          this.isLoadingSubject$.complete();
Thanks. This is because the `BehaviorSubject` is a cold observable. It won't emit anything until someone subscribes to it. And in general, I also understand any completed observable will no longer emit values. The change is correct 💯

2020-07-24 14:00 UTC, lbalmaceda approved these changes

2020-07-27 10:24 UTC, merged