[SDK-1847, SDK-1848] Add HttpInterceptor to attach access tokens to requests
auth0/auth0-angular pull request #18
Opened 2020-07-29 22:23 UTC by stevehobbsdev

### Description

This PR adds an Http Interceptor to automatically attach access tokens to outgoing requests that are using the built-in `HttpClient` type to make API calls.

Features:

- Configuration that allows the developer to dictate which API calls get which tokens
- Will accept strings, RegExp or an option that allows configuration for `getTokenSilently`
- Can specify `audience` and `scope` per-API definition
- Routes that are not matched by the `httpInterceptor` configuration will continue to work but will not have an access token attached

**Note:** While we can automatically register the Http Interceptor as part of the `AuthModule` setup, it may be better to allow the developer to specify this themselves. The interceptor is designed to be chainable and we can't guarantee we'd insert the interceptor into the right place. But, this could be configurable by adding an option that prevents automatic registration of the Http Interceptor if the developer chooses not to use it.

### Usage

Configure which routes should receive an access token:

```js
const AUTH0_CONFIG = {
    domain: 'your-domain.auth0.com',
    clientId: '<your client ID>',
    httpInterceptor: {
        allowedList: [
            '/api',      // use a simple string to match outgoing URL..
            /\/api-regex/,   // .. or a regex
            {
                uri: '/api'.   // or an object with a string
            },
            {
                uri: \/api-regex/    // or an object with regex
            },
            {
                // use an object with options for getTokenSilently
                uri: '/api',
                audience: 'http://localhost/',
                scope: 'read:data',
                ignoreCache: true
            }
        ]
    }
}
```

Register the Http Interceptor into the application module (this is as per [Provide the Module](https://angular.io/guide/http#provide-the-interceptor) docs):

```js
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';

// Retrieve the interceptor currently using a relative path - in the future this will be straight from '@auth0/auth0-angular'
import { AuthHttpInterceptor } from 'projects/auth0-angular/src/lib/auth.interceptor';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    HttpClientModule,
    AppRoutingModule,
    AuthModule.forRoot(AUTH0_CONFIG),
  ],
  providers: [
    { provide: HTTP_INTERCEPTORS, useClass: AuthHttpInterceptor, multi: true },
  ],
  bootstrap: [AppComponent],
})
```

Then, make the API call as normal:

```js
import { HttpClient } from '@angular/common/http';

http.get('/api').subscribe(result => console.log(result));
```

### Testing

- [X] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [X] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [X] All active GitHub checks for tests, formatting, and security are passing
- [X] The correct base branch is being used, if not `master`

2020-07-29 23:06 UTC, lbalmaceda requested changes

2020-07-29 23:06 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.config.ts
> +export interface HttpInterceptorRouteConfig extends GetTokenSilentlyOptions {
what are the pros/cons of extending vs providing the token silently options as a separate optional parameter? e.g. could breaking changes on the token option impact this object?

2020-07-29 23:06 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.config.ts
> +   * an access token is attached to the request in the "Authorization" header.
Do we want to link to docs on this bearer approach? i.e. https://tools.ietf.org/html/draft-ietf-oauth-v2-bearer-20#section-2.1

2020-07-29 23:06 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.config.ts
> +   * If the test does not pass, the request proceeds without the token attached.
I rather be explicit here

```suggestion
   * If the test does not pass, the request proceeds without the access token attached.
```

2020-07-29 23:06 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.interceptor.ts
> +            map(({ uri, ...options }) => options),
I guess these `...options` refer to the `GetTokenSilentlyOptions` I asked about above. I don't think this approach scales well. See, if you add another property in addition to the `uri` you have today, you'd need to refactor this line to update that. I think it could be avoided if instead of extending you accept 2 separate params for each object.

Are you confident the route config object will not be added more properties?

2020-07-29 23:06 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.interceptor.ts
> +            switchMap((token: string) => {
I'm not too familiar with the internals of the SDK. Is there any success scenario where this token will have a value of undefined or similar?

2020-07-29 23:06 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.interceptor.ts
> +          () => route !== null,
for me is clear because I just learned this, but if you anticipate this `iif` block will get larger, consider adding a comment explaining each param.
e.g.

```
iif(
  // condition
  ...
  // if route is defined
  ...
  // else, when route is not defined
}
```

could improve a bit the readability for maintainers

2020-07-29 23:06 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.interceptor.ts
> +      if (value instanceof RegExp) {
I'd avoid the else-if by swapping the clauses and relying on that we're always returning a value, so the next line already implies the case prior didn't evaluate to true.

```js

if (value === request.url) {
  return true;
}
if (value instanceof RegExp && value.test(request.url)) {
  return true;
}
```

2020-07-29 23:06 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.interceptor.ts
> +    if ((route as HttpInterceptorRouteConfig).uri) {
is there any chance that this cast could fail with some horrible exception? e.g. when the route is not of the given type. Wouldn't be safer a typeof check?

Also, the line below seems to do the exact same casting. Might as well cast it once above before the condition check, or even rely on the `someObject?.uri` syntax.

2020-07-29 23:06 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.interceptor.ts
> +    return from(this.config.httpInterceptor.allowedList).pipe(
In the `intercept` signature at the top of the file, you don't trust the `httpInterceptor` to be defined. Why would you here?

I think it doesn't hurt adding this null-check.
```suggestion
    return from(this.config.httpInterceptor?.allowedList).pipe(
```

2020-07-29 23:06 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.interceptor.spec.ts
> +  it('passes through for a request that does not need an access token', () => {
nit: I see we'll probably add more cases in the future. Maybe we could organize these into `describe` blocks for unprotected and protected routes.

2020-07-29 23:06 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.interceptor.spec.ts
> +    req.flush(testData);
since the `testData` doesn't matter here, would it make sense to extract that to a class variable, also the `req` (being set on each test) and calling `req.flush(TEST_DATA)` in the `afterEach()` ?

2020-07-29 23:06 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.interceptor.spec.ts
> +    httpClient.get<Data>('/non-api').subscribe((result) => {
this is the only one test not using the `fakeAsync` test helper and subscribing in-line. If there's no strong reason to do this, I'd suggest we use the same approach on every test.

2020-07-29 23:06 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.interceptor.spec.ts
> +  it('passes through the route options to getTokenSilently, without additional properties', fakeAsync((
nit: I find the test name a bit confusing but I cannot think of an alternative now. The "additional properties" is too generic

2020-07-30 11:59 UTC, stevehobbsdev commented on projects/auth0-angular/src/lib/auth.interceptor.ts
> +    return from(this.config.httpInterceptor.allowedList).pipe(
Mainly because this code is only executed if we have the appropriate configuration. The code you're referring to effectively blocks this code from being run if there is no interceptor config.

You're right, it doesn't hurt adding the check, I'm just now wondering what `from(null).pipe(..)` would do. At least without the null check we'd get a property access exception where we'd expect to have a value.

2020-07-30 12:03 UTC, stevehobbsdev commented on projects/auth0-angular/src/lib/auth.config.ts
> +export interface HttpInterceptorRouteConfig extends GetTokenSilentlyOptions {
I considered that option when writing this. The first thing I noticed is that the configuration becomes more verbose, but at the same time splitting it out into its own parameter is more explicit.

Something like:

```js
httpInterceptor: {
    allowedList: [
        {
            uri: '/api',
            tokenOptions: {
                audience: 'http://localhost/',
                scope: 'read:data'
         }
    ]
}
```

versus

```js
httpInterceptor: {
    allowedList: [
        {
            uri: '/api',
            audience: 'http://localhost/',
            scope: 'read:data'
        }
    ]
}
```

I don't have a strong preference either way but I think the simpler the better. Thoughts?

2020-07-30 12:09 UTC, stevehobbsdev commented on projects/auth0-angular/src/lib/auth.interceptor.spec.ts
> +  it('passes through for a request that does not need an access token', () => {
Sure, I can do that.

2020-07-30 13:41 UTC, stevehobbsdev commented on projects/auth0-angular/src/lib/auth.interceptor.spec.ts
> +    httpClient.get<Data>('/non-api').subscribe((result) => {
There's a technical reason why `fakeAsync` isn't used in this test; it's because this test doesn't invoke `getTokenSilently` (and thus doesn't need `fakeAsync`), which is Promise-based. Adding this in causes the test to fail as it's waiting on an outstanding timer to be completed.

2020-07-30 13:50 UTC, stevehobbsdev commented on projects/auth0-angular/src/lib/auth.interceptor.ts
> +          () => route !== null,
Good idea, I've added some comments here.

2020-07-30 13:51 UTC, stevehobbsdev commented on projects/auth0-angular/src/lib/auth.interceptor.ts
> +            map(({ uri, ...options }) => options),
Although I can't think of any now, I can imagine we might add more in the future. However, when we add them we'd hopefully add a unit test, and there will be other tests that would break that would prompt us to add these properties here.

However, I agree with you and don't particularly like this and this would be one of the benefits of extracting these options out to a separate property.

2020-07-30 13:52 UTC, stevehobbsdev commented on projects/auth0-angular/src/lib/auth.interceptor.ts
> +            switchMap((token: string) => {
No. You'll either get a string or an exception, which can be handled by using `catchError`.

2020-07-30 13:53 UTC, stevehobbsdev commented on projects/auth0-angular/src/lib/auth.interceptor.ts
> +            switchMap((token: string) => {
Incidentally, this is an area we may handle in the future but I wanted to discuss options for doing that. If `getTokenSilently` fails because we don't have a refresh token, for example, we could automatically redirect to the login page.

Just an example, but we could do something. I've added a card in Jira to investigate this in the EA phase.

2020-07-30 13:57 UTC, stevehobbsdev commented on projects/auth0-angular/src/lib/auth.interceptor.ts
> +      if (value instanceof RegExp) {
Much better! Thanks :)

2020-07-30 13:59 UTC, stevehobbsdev commented on projects/auth0-angular/src/lib/auth.interceptor.ts
> +    if ((route as HttpInterceptorRouteConfig).uri) {
Yes I want to refactor this bit anyway. TypeScript has a nice Type Guards feature we can make use of. There won't be a horrible type case exception though as none of this has any bearing at runtime; this is just to satisfy the static compiler.

2020-07-30 14:22 UTC, lbalmaceda commented on projects/auth0-angular/src/lib/auth.interceptor.ts
> +            switchMap((token: string) => {
that example sounds like something the SDK could handle. Although I'm not certain if that would be some "breaking change" in behavior. Is like embedding some "credentials manager" in that method

2020-07-30 14:51 UTC, stevehobbsdev commented on projects/auth0-angular/src/lib/auth.interceptor.spec.ts
> +    httpClient.get<Data>('/non-api').subscribe((result) => {
Missed of a call to `flush()`, which was causing the timer error. Fixed that now 👍

2020-07-30 15:29 UTC, lbalmaceda approved these changes

2020-07-30 20:49 UTC, merged