Add example for Standalone components and a more functional approach
auth0/auth0-angular pull request #443
Opened 2023-03-29 08:54 UTC by frederikprijck

### Description

Add example for Standalone components and a more functional approach 

### References

#442 

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not the default branch

2023-03-31 10:33 UTC, stevehobbsdev requested changes
Looks great, just highlighted a small typo 🎉

2023-03-31 10:33 UTC, stevehobbsdev commented on EXAMPLES.md
> +Untill we have built in support for these concepts, you will need to add a couple of small work arounds to leverage these concepts with our SDK:
```suggestion
Until we have built-in support for these concepts, you will need to add a couple of small workarounds to leverage these concepts with our SDK:
```

2023-04-03 07:58 UTC, frederikprijck commented
The implementation here will change once we merge https://github.com/auth0/auth0-angular/pull/445, so moving this to draft again.

2023-04-03 14:16 UTC, stevehobbsdev submitted a review, later dismissed

2023-04-03 14:16 UTC, frederikprijck commented on EXAMPLES.md
> +- Register our SDK using `provideAuth`.
```suggestion
- Register our SDK using `provideAuth0`.
```

2023-04-03 14:25 UTC, stevehobbsdev approved these changes

2023-04-03 15:05 UTC, merged